"""Base interfaces and data structures for the 6-stage security pipeline."""

from abc import ABC, abstractmethod
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field
from mcpath.risk_engine.models import SecurityEventRecord


class PipelineContext(BaseModel):
    """Execution context passed through the pipeline stages."""
    server_name: str
    tool_name: str
    arguments: Dict[str, Any] = Field(default_factory=dict)
    user_prompt: Optional[str] = None
    tool_definition: Optional[Dict[str, Any]] = None
    tool_response: Optional[Any] = None
    event_record: SecurityEventRecord


class StageResult(BaseModel):
    """Output generated by a single pipeline stage."""
    stage_name: str
    score: Optional[float] = None  # Graded score 0-100 (for stages 2-5)
    hard_block: bool = False       # Immediate gate (e.g. Stage 1 hash mismatch)
    passed: bool = True
    explanation: str = ""
    metadata: Dict[str, Any] = Field(default_factory=dict)


class BasePipelineStage(ABC):
    """Abstract base class for all MCPath pipeline stages."""

    def __init__(self, name: str):
        self.name = name

    @abstractmethod
    async def process_request(self, context: PipelineContext) -> StageResult:
        """Evaluate the pre-execution tool call."""
        pass

    async def process_response(self, context: PipelineContext) -> StageResult:
        """Evaluate the post-execution tool response (Stage 5 primarily)."""
        return StageResult(stage_name=self.name, passed=True, explanation="Response check not applicable")
